import Link from "next/link";

const hardwareComponents = [
  {
    icon: "🧠",
    title: "CPU",
    description:
      "The Central Processing Unit is the main processing component of a computer. It executes instructions and performs calculations.",
    topics: ["ALU", "Control Unit", "Registers"],
  },
  {
    icon: "💾",
    title: "RAM",
    description:
      "Random Access Memory temporarily stores data and programs that are currently being used by the computer.",
    topics: ["Volatile", "Fast Access", "Temporary Storage"],
  },
  {
    icon: "🧩",
    title: "Motherboard",
    description:
      "The motherboard is the main circuit board that connects the CPU, memory, storage and other hardware components.",
    topics: ["CPU Socket", "RAM Slots", "Expansion Slots"],
  },
  {
    icon: "⌨️",
    title: "Keyboard",
    description:
      "A keyboard is an input device used to enter text, numbers, commands and other information.",
    topics: ["Alphanumeric Keys", "Function Keys", "Control Keys"],
  },
  {
    icon: "🖱️",
    title: "Mouse",
    description:
      "A mouse is a pointing input device used to move the pointer, select items and interact with graphical interfaces.",
    topics: ["Click", "Double Click", "Scroll"],
  },
  {
    icon: "🖥️",
    title: "Monitor",
    description:
      "A monitor is an output device that displays text, images, videos and other information generated by the computer.",
    topics: ["LCD", "LED", "Resolution"],
  },
  {
    icon: "🖨️",
    title: "Printer",
    description:
      "A printer is an output device that produces a physical copy of digital documents, images and other information.",
    topics: ["Inkjet", "Laser", "Print Quality"],
  },
  {
    icon: "🔊",
    title: "Speakers",
    description:
      "Speakers are output devices that convert digital audio signals into sound that can be heard by the user.",
    topics: ["Audio", "Sound Output", "Multimedia"],
  },
  {
    icon: "💿",
    title: "Storage Devices",
    description:
      "Storage devices are used to save programs, documents, photos, videos and other digital information.",
    topics: ["HDD", "SSD", "Pen Drive"],
  },
];

const hardwareCategories = [
  ["⌨️", "Input Hardware", "Used to enter data and instructions into a computer."],
  ["🧠", "Processing Hardware", "Processes data and executes computer instructions."],
  ["🖥️", "Output Hardware", "Presents processed information to the user."],
  ["💾", "Storage Hardware", "Stores data and information for temporary or long-term use."],
];

const importantPoints = [
  "Hardware refers to the physical parts of a computer.",
  "CPU is responsible for executing instructions and processing data.",
  "The motherboard connects major computer components.",
  "RAM is temporary and volatile memory.",
  "Keyboard and mouse are common input devices.",
  "Monitor and printer are common output devices.",
  "HDD and SSD are storage devices.",
  "Hardware requires software instructions to perform useful tasks.",
  "Input devices send data to the computer.",
  "Output devices present processed information to the user.",
];

const hardwareFacts = [
  ["CPU", "Processes instructions"],
  ["RAM", "Temporary working memory"],
  ["Motherboard", "Connects major components"],
  ["Keyboard", "Input device"],
  ["Monitor", "Output device"],
  ["SSD", "Storage device"],
];

export default function HardwarePage() {
  return (
    <main className="min-h-screen bg-white text-slate-800">

      {/* HEADER */}
      <header className="sticky top-0 z-50 border-b border-slate-200 bg-white/95 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 lg:px-8">

          <Link href="/" className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-600 text-xl font-bold text-white shadow-lg">
              RI
            </div>

            <div>
              <h1 className="text-lg font-bold text-slate-900">
                Rishi Infotech
              </h1>
              <p className="text-xs font-medium text-blue-600">
                Learning Hub
              </p>
            </div>
          </Link>

          <nav className="hidden items-center gap-6 lg:flex">
            <Link href="/" className="font-medium hover:text-blue-600">
              Home
            </Link>

            <Link href="/learn" className="font-medium text-blue-600">
              Learn
            </Link>

            <Link href="/practice" className="font-medium hover:text-blue-600">
              Practice
            </Link>

            <Link href="/ai-hub" className="font-medium hover:text-blue-600">
              AI Hub
            </Link>

            <Link
              href="/developer-hub"
              className="font-medium hover:text-blue-600"
            >
              Developer
            </Link>

            <Link
              href="/downloads"
              className="font-medium hover:text-blue-600"
            >
              Downloads
            </Link>
          </nav>

          <Link
            href="/contact"
            className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-md hover:bg-blue-700"
          >
            Contact
          </Link>

        </div>
      </header>

      {/* HERO */}
      <section className="relative overflow-hidden bg-gradient-to-br from-blue-700 via-blue-600 to-cyan-500">

        <div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-white/10 blur-3xl" />
        <div className="absolute -bottom-40 -left-20 h-96 w-96 rounded-full bg-cyan-300/20 blur-3xl" />

        <div className="relative mx-auto max-w-7xl px-4 py-16 lg:px-8 lg:py-20">

          <Link
            href="/learn/computer"
            className="inline-flex rounded-full bg-white/15 px-4 py-2 text-sm font-semibold text-white backdrop-blur hover:bg-white/20"
          >
            ← Computer Chapters
          </Link>

          <div className="mt-8 flex items-center gap-5">

            <div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-3xl bg-white text-5xl shadow-xl">
              🖥️
            </div>

            <div>
              <p className="font-semibold text-blue-100">
                COMPUTER HARDWARE
              </p>

              <h2 className="text-3xl font-black text-white sm:text-5xl">
                Computer Hardware
              </h2>
            </div>

          </div>

          <p className="mt-7 max-w-3xl text-lg leading-8 text-blue-50">
            Learn about the physical components of a computer, including
            the CPU, motherboard, memory, input devices, output devices
            and storage hardware.
          </p>

          <div className="mt-8 flex flex-col gap-3 sm:flex-row">

            <a
              href="#hardware"
              className="rounded-xl bg-white px-7 py-3.5 text-center font-bold text-blue-700 shadow-xl hover:scale-105"
            >
              🖥️ Start Learning
            </a>

            <Link
              href="/practice/mcq"
              className="rounded-xl border-2 border-white/60 px-7 py-3.5 text-center font-bold text-white hover:bg-white hover:text-blue-700"
            >
              📝 Practice MCQs
            </Link>

          </div>

        </div>
      </section>

      {/* BREADCRUMB */}
      <div className="border-b border-slate-200 bg-white">
        <div className="mx-auto max-w-7xl px-4 py-4 text-sm lg:px-8">

          <Link href="/learn" className="text-blue-600 hover:underline">
            Learn
          </Link>

          <span className="mx-2 text-slate-400">/</span>

          <Link
            href="/learn/computer"
            className="text-blue-600 hover:underline"
          >
            Computer
          </Link>

          <span className="mx-2 text-slate-400">/</span>

          <span className="text-slate-500">
            Computer Hardware
          </span>

        </div>
      </div>

      {/* MAIN */}
      <section id="hardware" className="py-16">

        <div className="mx-auto max-w-7xl px-4 lg:px-8">

          {/* INTRO */}
          <div className="max-w-4xl">

            <p className="font-bold uppercase tracking-widest text-blue-600">
              Chapter
            </p>

            <h2 className="mt-3 text-4xl font-black text-slate-900">
              What is Computer Hardware?
            </h2>

            <p className="mt-5 text-lg leading-8 text-slate-600">
              Computer hardware refers to the physical components of a
              computer system that can be seen and touched. These components
              work together to accept input, process information, store data
              and produce output.
            </p>

          </div>

          {/* CATEGORIES */}
          <section className="mt-12">

            <p className="font-bold uppercase tracking-widest text-cyan-600">
              Classification
            </p>

            <h2 className="mt-3 text-3xl font-black text-slate-900">
              Main Categories of Hardware
            </h2>

            <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">

              {hardwareCategories.map(([icon, title, text]) => (
                <div
                  key={title}
                  className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"
                >

                  <div className="text-4xl">
                    {icon}
                  </div>

                  <h3 className="mt-4 text-xl font-black text-slate-900">
                    {title}
                  </h3>

                  <p className="mt-3 text-sm leading-7 text-slate-600">
                    {text}
                  </p>

                </div>
              ))}

            </div>

          </section>

          {/* COMPONENTS */}
          <section className="mt-16">

            <p className="font-bold uppercase tracking-widest text-blue-600">
              Hardware Components
            </p>

            <h2 className="mt-3 text-3xl font-black text-slate-900">
              Important Computer Hardware
            </h2>

            <p className="mt-4 max-w-3xl leading-7 text-slate-600">
              A computer system contains many hardware components. Each
              component performs a specific function and works together with
              other components.
            </p>

            <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">

              {hardwareComponents.map((item) => (
                <article
                  key={item.title}
                  className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"
                >

                  <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-3xl">
                    {item.icon}
                  </div>

                  <h3 className="mt-5 text-xl font-black text-slate-900">
                    {item.title}
                  </h3>

                  <p className="mt-3 text-sm leading-7 text-slate-600">
                    {item.description}
                  </p>

                  <div className="mt-5 flex flex-wrap gap-2">
                    {item.topics.map((topic) => (
                      <span
                        key={topic}
                        className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600"
                      >
                        {topic}
                      </span>
                    ))}
                  </div>

                </article>
              ))}

            </div>

          </section>

          {/* INPUT PROCESS OUTPUT */}
          <section className="mt-16 rounded-3xl bg-blue-50 p-8">

            <p className="font-bold uppercase tracking-widest text-blue-600">
              Basic Concept
            </p>

            <h2 className="mt-3 text-3xl font-black text-slate-900">
              How Hardware Works Together
            </h2>

            <p className="mt-4 max-w-3xl leading-7 text-slate-600">
              Computer hardware components work together as a system. Data
              enters through input devices, is processed by the CPU and the
              result is presented through output devices. Storage devices
              keep information for later use.
            </p>

            <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">

              {[
                ["1", "Input", "Keyboard, mouse and scanner"],
                ["2", "Processing", "CPU and memory"],
                ["3", "Storage", "HDD, SSD and other storage"],
                ["4", "Output", "Monitor, printer and speakers"],
              ].map(([number, title, text]) => (
                <div
                  key={number}
                  className="rounded-2xl bg-white p-6 text-center shadow-sm"
                >

                  <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 font-black text-white">
                    {number}
                  </div>

                  <h3 className="mt-4 font-black text-slate-900">
                    {title}
                  </h3>

                  <p className="mt-2 text-sm leading-6 text-slate-500">
                    {text}
                  </p>

                </div>
              ))}

            </div>

          </section>

          {/* INTERNAL VS EXTERNAL */}
          <section className="mt-16">

            <p className="font-bold uppercase tracking-widest text-indigo-600">
              Hardware Types
            </p>

            <h2 className="mt-3 text-3xl font-black text-slate-900">
              Internal and External Hardware
            </h2>

            <div className="mt-8 grid gap-6 md:grid-cols-2">

              <div className="rounded-3xl border border-blue-100 bg-blue-50 p-8">

                <div className="text-4xl">
                  🧩
                </div>

                <h3 className="mt-4 text-2xl font-black text-slate-900">
                  Internal Hardware
                </h3>

                <p className="mt-3 leading-7 text-slate-600">
                  Internal hardware components are installed inside the
                  computer case or device and are essential for processing,
                  memory and system operation.
                </p>

                <div className="mt-6 space-y-2">
                  {[
                    "CPU",
                    "RAM",
                    "Motherboard",
                    "Power Supply",
                    "Graphics Card",
                  ].map((item) => (
                    <div
                      key={item}
                      className="rounded-xl bg-white p-3 text-sm font-semibold text-blue-700"
                    >
                      ✓ {item}
                    </div>
                  ))}
                </div>

              </div>

              <div className="rounded-3xl border border-cyan-100 bg-cyan-50 p-8">

                <div className="text-4xl">
                  🔌
                </div>

                <h3 className="mt-4 text-2xl font-black text-slate-900">
                  External Hardware
                </h3>

                <p className="mt-3 leading-7 text-slate-600">
                  External hardware devices are connected to the computer
                  from outside and are often used for input, output,
                  communication or additional storage.
                </p>

                <div className="mt-6 space-y-2">
                  {[
                    "Keyboard",
                    "Mouse",
                    "Printer",
                    "External Drive",
                    "Webcam",
                  ].map((item) => (
                    <div
                      key={item}
                      className="rounded-xl bg-white p-3 text-sm font-semibold text-cyan-700"
                    >
                      ✓ {item}
                    </div>
                  ))}
                </div>

              </div>

            </div>

          </section>

          {/* IMPORTANT TERMS */}
          <section className="mt-16">

            <div className="text-center">

              <p className="font-bold uppercase tracking-widest text-cyan-600">
                Quick Revision
              </p>

              <h2 className="mt-3 text-3xl font-black text-slate-900">
                Important Hardware Terms
              </h2>

            </div>

            <div className="mx-auto mt-8 max-w-4xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">

              {hardwareFacts.map(([short, full], index) => (
                <div
                  key={short}
                  className={`grid grid-cols-2 ${
                    index !== hardwareFacts.length - 1
                      ? "border-b border-slate-200"
                      : ""
                  }`}
                >

                  <div className="p-5 font-black text-blue-600">
                    {short}
                  </div>

                  <div className="p-5 text-sm text-slate-600">
                    {full}
                  </div>

                </div>
              ))}

            </div>

          </section>

          {/* IMPORTANT POINTS */}
          <section className="mt-16">

            <p className="font-bold uppercase tracking-widest text-blue-600">
              Exam Revision
            </p>

            <h2 className="mt-3 text-3xl font-black text-slate-900">
              Important Points
            </h2>

            <div className="mt-8 grid gap-3 md:grid-cols-2">

              {importantPoints.map((item, index) => (
                <div
                  key={item}
                  className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-5"
                >

                  <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-100 text-xs font-black text-blue-600">
                    {index + 1}
                  </span>

                  <p className="text-sm leading-6 text-slate-600">
                    {item}
                  </p>

                </div>
              ))}

            </div>

          </section>

          {/* PRACTICE */}
          <section className="mt-16 rounded-3xl bg-gradient-to-br from-blue-700 to-cyan-500 p-8 text-white shadow-2xl md:p-10">

            <p className="font-bold uppercase tracking-widest text-blue-100">
              Test Your Knowledge
            </p>

            <h2 className="mt-3 text-3xl font-black">
              Ready for Hardware MCQs?
            </h2>

            <p className="mt-4 max-w-2xl leading-7 text-blue-50">
              Test your knowledge of CPU, motherboard, memory, input devices,
              output devices and storage hardware.
            </p>

            <div className="mt-7 flex flex-col gap-3 sm:flex-row">

              <Link
                href="/practice/mcq"
                className="rounded-xl bg-white px-7 py-3.5 text-center font-bold text-blue-700 shadow-lg hover:scale-105"
              >
                📝 Start MCQ
              </Link>

              <Link
                href="/practice/mock-tests"
                className="rounded-xl border-2 border-white/60 px-7 py-3.5 text-center font-bold text-white hover:bg-white hover:text-blue-700"
              >
                🎯 Mock Test
              </Link>

            </div>

          </section>

        </div>
      </section>

      {/* NAVIGATION */}
      <section className="border-t border-slate-200 bg-slate-50 py-10">

        <div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-4 sm:flex-row lg:px-8">

          <Link
            href="/learn/computer/introduction"
            className="rounded-xl border border-slate-200 bg-white px-6 py-3 text-center font-bold text-slate-700 hover:border-blue-300 hover:text-blue-600"
          >
            ← Previous: Introduction
          </Link>

          <Link
            href="/learn/computer/software"
            className="rounded-xl bg-blue-600 px-6 py-3 text-center font-bold text-white hover:bg-blue-700"
          >
            Next: Computer Software →
          </Link>

        </div>

      </section>

      {/* FOOTER */}
      <footer className="bg-slate-900 text-white">

        <div className="mx-auto max-w-7xl px-4 py-12 lg:px-8">

          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">

            <div>
              <h2 className="text-xl font-bold">
                Rishi Infotech
              </h2>

              <p className="mt-3 text-sm leading-6 text-slate-400">
                Learning, practice, AI tools and developer utilities
                in one place.
              </p>
            </div>

            <div>
              <h3 className="font-semibold">
                Learning
              </h3>

              <div className="mt-4 space-y-2 text-sm text-slate-400">

                <Link href="/learn" className="block hover:text-white">
                  All Subjects
                </Link>

                <Link
                  href="/learn/computer"
                  className="block hover:text-white"
                >
                  Computer
                </Link>

                <Link
                  href="/learn/physics"
                  className="block hover:text-white"
                >
                  Physics
                </Link>

              </div>
            </div>

            <div>
              <h3 className="font-semibold">
                Practice
              </h3>

              <div className="mt-4 space-y-2 text-sm text-slate-400">

                <Link href="/practice" className="block hover:text-white">
                  Practice Center
                </Link>

                <Link
                  href="/practice/mcq"
                  className="block hover:text-white"
                >
                  MCQ Quiz
                </Link>

                <Link
                  href="/practice/mock-tests"
                  className="block hover:text-white"
                >
                  Mock Tests
                </Link>

              </div>
            </div>

            <div>
              <h3 className="font-semibold">
                Tools
              </h3>

              <div className="mt-4 space-y-2 text-sm text-slate-400">

                <Link href="/ai-hub" className="block hover:text-white">
                  AI Hub
                </Link>

                <Link
                  href="/developer-hub"
                  className="block hover:text-white"
                >
                  Developer Hub
                </Link>

                <Link
                  href="/dictionary"
                  className="block hover:text-white"
                >
                  Dictionary
                </Link>

              </div>
            </div>

          </div>

          <div className="mt-10 border-t border-slate-700 pt-6 text-center text-sm text-slate-500">
            © 2026 Rishi Infotech Learning Hub. All rights reserved.
          </div>

        </div>

      </footer>

    </main>
  );
}
